### ISSUE TITLE
Handlebars 2.0.0

### ISSUE THREAD

**Issue by husayt** [jblotus/Try-Handlebars.js#13]
New handlebars 2 has many issues fixed and some cool additions, like `lookup` helper.

 Any plans, for switching try-handlabrs to it? Should be quite safe, as I don't know of any major breaking changes.  

BTW, thanks for very useful tool.

**Comment by jblotus** [comment]
Hey there, really sorry for the delayed response, for some reason these notifications just got buried in my inbox.

Ideally I would like to make the specific version of handlebars selectable, perhaps from a dropdown. perhaps highlighting some of the newer features as well for handlebars2.
