### ISSUE TITLE
responsive layout

### ISSUE THREAD

**Issue by mattkime** [jblotus/Try-Handlebars.js#14]

**Comment by jblotus** [comment]
closing this, thanks to your contributions we should be able to pull this off

**Comment by alexwebgr** [comment]
i would suggest to reverse the merge of this pull request 
makkkime failed to properly merge master into his branch which resulted into the issues reported earlier 
he also committed commented code and whitespace characters 

@mattkime revert and branch out from master then add the responsive functionality 
make small commits with descriptive messages and only touch a few files each time 

great effort but needs some work before merged to master 

alex

**Comment by jblotus** [comment]
@alexwebgr part of this is my responsibility, i had some tweaks that i sent out to matt in a patch file that had some whitespace issues.

**Comment by jblotus** [comment]
i think reverting at this point might not make sense since i already have a few more commits ahead of the merge that address some of the issues. i would just like to move forward and clean up anything that is problematic.

**Comment by mattkime** [comment]
released

**Comment by alexwebgr** [comment]
@mattkime i dont really plan to get involved

i just saw your pull request and didnt like a few things 

you guys go on with your plans 

i like what you did in the new version of the website i dont really like the drop down though i think it might easier to use if there were buttons instead 

alex

**Comment by jblotus** [comment]
@alexwebgr i do appreciate your contributions and opinion thank you. i also agree about the drop down I have similar mixed feelings but at the same time it may fit a responsive layout more? I truly don't know.

**Comment by mattkime** [comment]
i'm happy to consider other interface ideas. i chose the select because its simple and compact. 

I plan on adding a lot more examples. I might have a better idea of whats needed once there's a large number.

**Comment by jblotus** [comment]
@mattkime i would say lets keep the select for now and see how it goes =]

**Comment by alexwebgr** [comment]
buttons  in tabs !!!
http://jsfiddle.net/a0sc2jvm/1/
