### ISSUE TITLE
WIP-responsive funky colors in html preview for some examples

### ISSUE THREAD

**Issue by jblotus** [jblotus/Try-Handlebars.js#25]

**Comment by mattkime** [comment]
I agree that the colors are funky but i'm uncertain about what funk to keep and what to toss. we're demoing templates rather than styling so i just assume keep all text the same color. 

i'm happy to jump in and grab this if you can clarify.

**Comment by jblotus** [comment]
you make a good point and to be honest looking at it again i don't feel that strongly about it either.
